#!/usr/bin/env bash
# print content of current directory

files=$(ls)
for file in $files
do
	if [[ $file != .* && $file == *-* ]]
	then
		output=$(echo "$file" | cut -d'-' -f2)
		echo "$output"
	fi
done
